In [ ]:
import numpy as np #2005 by Travis Oliphant
print(np.__version__)

1.23.5


In [ ]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly tr

- Why numpy
- mathematical function
- Faster

In [ ]:
l = [1, 3,54 ,7,8]
arr = np.array(l)
arr

array([ 1,  3, 54,  7,  8])

In [ ]:
type(np.array(l))

numpy.ndarray

In [ ]:
arr.ndim

1

In [ ]:
l = [1, 2, 4,6, "Rishi"]
arr1 = np.array(l)
arr1

array(['1', '2', '4', '6', 'Rishi'], dtype='<U21')

In [ ]:
arr.ndim

1

In [ ]:
arr

array([ 1,  3, 54,  7,  8])

In [ ]:
arr1 = np.array([[1,2,3], [4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr1.ndim

2

In [ ]:
l = [1,2,3,4]
np.array(l)

array([1, 2, 3, 4])

In [ ]:
mat = np.matrix(l) #matris will be by default 2nd
mat

matrix([[1, 2, 3, 4]])

In [ ]:
np.matrix([[1,2], [5,6], [7,8]])

matrix([[1, 2],
        [5, 6],
        [7, 8]])

In [ ]:
np.matrix([[[1,2], [5,6], [7,8]]])

ValueError: matrix must be 2-dimensional

In [ ]:
np.array([[[1, 2], [5, 6], [7, 8]]])

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [ ]:
# more way to convert to array
np.array([[[1,2], [5,6], [7,8]]])

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [ ]:
#converyt the input to an ndarray, but pass ndarray subclass through.
np.asanyarray([[[1, 2], [5, 6], [7, 8]]])

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [ ]:
mat

matrix([[1, 2, 3, 4]])

In [ ]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4]])

In [ ]:
np.asarray([[[1,2], [5,7], [8,9]]])

array([[[1, 2],
        [5, 7],
        [8, 9]]])

In [ ]:
t = ([1, 2, 3], [4, 5, 6])
type(t)

tuple

In [ ]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a = 5
np.array(a)

array(5)

In [ ]:
l = [1, 2, 3, 4, 5]
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [ ]:
a = arr
a

array([1, 2, 3, 4, 5])

In [ ]:
a[0] = 1000
a

array([1000,    2,    3,    4,    5])

In [ ]:
arr

array([1000,    2,    3,    4,    5])

In [ ]:
b = a.copy()
b[0] = 2000
b

array([2000,    2,    3,    4,    5])

In [ ]:
a

array([1000,    2,    3,    4,    5])

**to create array >> .array, .asasrray, ,asanyarray, deep coy, shallow copy**

In [ ]:
np.fromfunction(lambda i, j : i==j, (3, 3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
arr

array([1000,    2,    3,    4,    5])

In [ ]:
arr.shape

(5,)

In [ ]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr1.shape

(2, 3)

In [ ]:
arr1.size

6

In [ ]:
arr.size

5

In [ ]:
np.fromfunction(lambda i, j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [ ]:
for i in range(5):
  print(i)

0
1
2
3
4


In [ ]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [ ]:
list(i for i in range(5))

[0, 1, 2, 3, 4]

In [ ]:
list(range(5))

[0, 1, 2, 3, 4]

In [ ]:
iterable = (i*i for i in range(5))

In [ ]:
np.fromiter(iterable, int)

array([ 0,  1,  4,  9, 16])

In [ ]:
np.fromstring('23 34 67', sep = ' ')

array([23., 34., 67.])

In [ ]:
np.fromstring('Abhi. Ajay, govind', sep = ' ')

<ipython-input-66-428e4e7f23db>:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring('Abhi. Ajay, govind', sep = ' ')


array([], dtype=float64)

In [ ]:
arr

array([1000,    2,    3,    4,    5])

In [ ]:
arr.size

5

In [ ]:
arr.shape

(5,)

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
l = [1, 2, 3, "ajay"]
arr = np.array(l)
arr.dtype

dtype('<U21')

In [ ]:
arr

array(['1', '2', '3', 'ajay'], dtype='<U21')

In [ ]:
list(range(5))

[0, 1, 2, 3, 4]

In [ ]:
range(5)

range(0, 5)

In [ ]:
list(range(1.0, 2.0, 3.10))

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
list(np.arange(0.1, 10.2, 0.9))

[0.1,
 1.0,
 1.9000000000000001,
 2.8000000000000003,
 3.7,
 4.6,
 5.5,
 6.3999999999999995,
 7.3,
 8.2,
 9.1,
 10.0]

In [ ]:
np.linspace(1, 5, 20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [ ]:
np.logspace(1, 5, 10, base = 2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [ ]:
np.logspace(1, 5, 10, base =2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [ ]:
np.logspace(1, 5, 10, base = 10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [ ]:
arr1 = np.zeros(5)
arr1.shape

(5,)

In [ ]:
arr1

array([0., 0., 0., 0., 0.])

In [ ]:
arr1.ndim

1

In [ ]:
arr2 = np.zeros((3,4))
arr2.shape

(3, 4)

In [ ]:
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr2.ndim

2

In [ ]:
arr3 = np.zeros((1, 3, 4))
arr3.shape

(1, 3, 4)

In [ ]:
arr3.ndim

3

In [ ]:
arr4 = np.zeros((1, 1, 3, 4))
arr4.shape

(1, 1, 3, 4)

In [ ]:
arr4.ndim

4

In [ ]:
arr4

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
arr = np.ones((3, 4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [ ]:
arr * 6

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [ ]:
np.array([[[[[[[[[[1,1,1,1,1]]]]]]]]]])

array([[[[[[[[[[1, 1, 1, 1, 1]]]]]]]]]])

In [ ]:
np.twos((2,3))

AttributeError: module 'numpy' has no attribute 'twos'

In [ ]:
l = [1, 2, 3,  4, 5, "Prince"]
arr = np.array(l)
arr.dtype

dtype('<U21')

In [ ]:
arr

array(['1', '2', '3', '4', '5', 'Prince'], dtype='<U21')

In [ ]:
import numpy as np
arr = np.ones((3, 4))

In [ ]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr + 5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [ ]:
arr * 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
np.empty((3, 4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
np.eye(3, dtype = int) #n*n matrix,  to calculate inverse of matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
import pandas as pd
pd.DataFrame(arr)

0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0

In [ ]:
import random
random.choice('Abhi')


'i'

In [ ]:
random.randrange(1, 10)

6

In [ ]:
random.random() #random no. is generated b/w 0(include), 1 will be excluced

0.7270943135521519

In [ ]:
lis = [1, 2, 3, 4, 5]
random.shuffle(lis)
lis

[2, 4, 3, 5, 1]

In [ ]:
random.uniform(7, 14)

13.5555792043108

In [ ]:
np.array([])

array([], dtype=float64)

In [ ]:
np.random.random_sample()

0.8424338676281604

In [ ]:
type(np.random.random_sample())

float

In [ ]:
np.random.random_sample((5,))

array([0.30541385, 0.05483288, 0.00926386, 0.23196546, 0.65345912])

In [ ]:
np.random.rand(1)

array([0.5116648])

In [ ]:
np.random.rand(2, 9)

array([[0.15319031, 0.28261833, 0.56356515, 0.41747938, 0.28258071,
        0.99966117, 0.47102091, 0.11539365, 0.58965766],
       [0.03095963, 0.07485504, 0.39420867, 0.8614796 , 0.1165905 ,
        0.45116891, 0.09312644, 0.60553183, 0.31291462]])

In [ ]:
np.random.randn(2, 9)

array([[-0.20628826, -0.19058219, -0.46771446,  0.00172544, -0.31815171,
         1.30743517,  1.51286721,  1.24846595,  1.48535266],
       [ 1.48800025, -0.12277662, -1.2982699 ,  0.31097846,  1.3792484 ,
         0.09908362,  0.24098144,  0.8985636 , -0.32923557]])

In [ ]:
np.random.random_sample()

0.21872182558282205

In [ ]:
np.random.randint(1, 5, size =(3, 4))

array([[3, 3, 2, 3],
       [4, 3, 1, 3],
       [2, 1, 3, 4]])

In [ ]:
arr = np.random.randint(1, 5, size = (3,4))

In [ ]:
arr

array([[3, 4, 1, 3],
       [2, 2, 4, 3],
       [2, 2, 2, 2]])

In [ ]:
arr.size

12

In [ ]:
arr.shape

(3, 4)

In [ ]:
arr.ndim

2

In [ ]:
arr

array([[3, 4, 1, 3],
       [2, 2, 4, 3],
       [2, 2, 2, 2]])

In [ ]:
arr.reshape(2, 6) #array size can not change, multiples of array size

array([[3, 4, 1, 3, 2, 2],
       [4, 3, 2, 2, 2, 2]])

In [ ]:
arr.reshape(6, 2)

array([[3, 4],
       [1, 3],
       [2, 2],
       [4, 3],
       [2, 2],
       [2, 2]])

In [153]:
arr.reshape(12,)

array([3, 4, 1, 3, 2, 2, 4, 3, 2, 2, 2, 2])

In [154]:
arr.reshape(12, 1)

array([[3],
       [4],
       [1],
       [3],
       [2],
       [2],
       [4],
       [3],
       [2],
       [2],
       [2],
       [2]])

In [155]:
arr.reshape(12,2)

ValueError: cannot reshape array of size 12 into shape (12,2)

In [156]:
arr.reshape(4,3)

array([[3, 4, 1],
       [3, 2, 2],
       [4, 3, 2],
       [2, 2, 2]])

In [157]:
arr.reshape(3,4)

array([[3, 4, 1, 3],
       [2, 2, 4, 3],
       [2, 2, 2, 2]])

In [158]:
arr

array([[3, 4, 1, 3],
       [2, 2, 4, 3],
       [2, 2, 2, 2]])

In [159]:
arr.reshape(4, -1)

array([[3, 4, 1],
       [3, 2, 2],
       [4, 3, 2],
       [2, 2, 2]])

In [160]:
arr.reshape(4, -100)

array([[3, 4, 1],
       [3, 2, 2],
       [4, 3, 2],
       [2, 2, 2]])

In [161]:
arr.reshape(-1, 4)

array([[3, 4, 1, 3],
       [2, 2, 4, 3],
       [2, 2, 2, 2]])

In [162]:
arr

array([[3, 4, 1, 3],
       [2, 2, 4, 3],
       [2, 2, 2, 2]])

In [163]:
arr.reshape(12, ).base

array([[3, 4, 1, 3],
       [2, 2, 4, 3],
       [2, 2, 2, 2]])

In [164]:
arr

array([[3, 4, 1, 3],
       [2, 2, 4, 3],
       [2, 2, 2, 2]])

In [165]:
arr.size

12

In [166]:
arr.reshape(1, 2, 2, 3)

array([[[[3, 4, 1],
         [3, 2, 2]],

        [[4, 3, 2],
         [2, 2, 2]]]])

In [167]:
arr.reshape(4,3,1)

array([[[3],
        [4],
        [1]],

       [[3],
        [2],
        [2]],

       [[4],
        [3],
        [2]],

       [[2],
        [2],
        [2]]])

In [176]:
arr.reshape(1, 1, 1, 1, 1, 2, 1, 2, 3)

array([[[[[[[[[3, 4, 1],
              [3, 2, 2]]],


            [[[4, 3, 2],
              [2, 2, 2]]]]]]]]])

In [174]:
arr.reshape(1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 3)

array([[[[[[[[[[[[3, 4, 1],
                 [3, 2, 2]],

                [[4, 3, 2],
                 [2, 2, 2]]]]]]]]]]]])

In [177]:
lis = [1, 2, 3, 4]
arr = np.array(lis)

In [178]:
arr

array([1, 2, 3, 4])

In [179]:
arr.ndim

1

In [180]:
arr2 = np.array([[2, 3], [4, 5]])
arr2

array([[2, 3],
       [4, 5]])

In [182]:
arr2.ndim

2

In [183]:
arr2 = np.zeros((3,4))
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [184]:
arr.ndim

1

3rows 4 coloumn
- 2d array + 1d

In [185]:
arr3 = np.zeros((1, 3, 4))
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [186]:
arr3.ndim

3

In [187]:
arr3.shape

(1, 3, 4)

3rows, 4col
- 2d array + 1d +1d

In [188]:
arr4 = np.zeros((1, 1, 3, 4))

In [189]:
arr4

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [190]:
arr4.ndim

4

In [191]:
arr4.shape

(1, 1, 3, 4)

In [192]:
arr3 = np.zeros((3, 3, 4))
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [193]:
arr3.ndim

3

In [194]:
arr3.shape

(3, 3, 4)

In [196]:
arr1 = np.random.randint(1, 10, (5, 6))
arr1

array([[2, 1, 5, 9, 7, 7],
       [5, 7, 5, 3, 1, 8],
       [4, 3, 8, 6, 1, 3],
       [5, 8, 2, 8, 3, 6],
       [7, 3, 1, 6, 4, 8]])

In [197]:
arr1 > 5

array([[False, False, False,  True,  True,  True],
       [False,  True, False, False, False,  True],
       [False, False,  True,  True, False, False],
       [False,  True, False,  True, False,  True],
       [ True, False, False,  True, False,  True]])

In [198]:
arr1[arr1 > 5]

array([9, 7, 7, 7, 8, 8, 6, 8, 8, 6, 7, 6, 8])

In [199]:
arr1[arr1 < 5]

array([2, 1, 3, 1, 4, 3, 1, 3, 2, 3, 3, 1, 4])

In [200]:
arr1

array([[2, 1, 5, 9, 7, 7],
       [5, 7, 5, 3, 1, 8],
       [4, 3, 8, 6, 1, 3],
       [5, 8, 2, 8, 3, 6],
       [7, 3, 1, 6, 4, 8]])

In [201]:
arr

array([1, 2, 3, 4])

In [202]:
arr[0]

1

In [203]:
arr1


array([[2, 1, 5, 9, 7, 7],
       [5, 7, 5, 3, 1, 8],
       [4, 3, 8, 6, 1, 3],
       [5, 8, 2, 8, 3, 6],
       [7, 3, 1, 6, 4, 8]])

0th = 1st row in continuation and 0th and 2nd 2nd col

In [205]:
arr1[0:2, [0,2]]

array([[2, 5],
       [5, 5]])

slicing on the both row & col

In [206]:
arr1[0:2, 1:3]

array([[1, 5],
       [7, 5]])

In [207]:
arr1[0:2, [0, 1]]


array([[2, 1],
       [5, 7]])

In [208]:
arr1

array([[2, 1, 5, 9, 7, 7],
       [5, 7, 5, 3, 1, 8],
       [4, 3, 8, 6, 1, 3],
       [5, 8, 2, 8, 3, 6],
       [7, 3, 1, 6, 4, 8]])

In [209]:
arr1[2:5]

array([[4, 3, 8, 6, 1, 3],
       [5, 8, 2, 8, 3, 6],
       [7, 3, 1, 6, 4, 8]])

In [210]:
arr1[2:5, 0:2] #slicing

array([[4, 3],
       [5, 8],
       [7, 3]])

In [211]:
arr1[[2,4]]

array([[4, 3, 8, 6, 1, 3],
       [7, 3, 1, 6, 4, 8]])

In [212]:
arr1

array([[2, 1, 5, 9, 7, 7],
       [5, 7, 5, 3, 1, 8],
       [4, 3, 8, 6, 1, 3],
       [5, 8, 2, 8, 3, 6],
       [7, 3, 1, 6, 4, 8]])

In [213]:
arr1[[2, 4]] #selecting specific coloumn

array([[4, 3, 8, 6, 1, 3],
       [7, 3, 1, 6, 4, 8]])

In [214]:
arr1

array([[2, 1, 5, 9, 7, 7],
       [5, 7, 5, 3, 1, 8],
       [4, 3, 8, 6, 1, 3],
       [5, 8, 2, 8, 3, 6],
       [7, 3, 1, 6, 4, 8]])

In [216]:
arr1[2:4, [1, 3]]

array([[3, 6],
       [8, 8]])

In [218]:
arr1 = np.random.randint(1, 3, (3,3))
arr2 = np.random.randint(1, 3, (3,3))

In [219]:
arr1

array([[1, 1, 2],
       [2, 1, 1],
       [2, 2, 1]])

In [220]:
arr2

array([[2, 2, 1],
       [2, 1, 1],
       [2, 1, 1]])

In [221]:
arr1 + arr2

array([[3, 3, 3],
       [4, 2, 2],
       [4, 3, 2]])

In [222]:
arr1 - arr2

array([[-1, -1,  1],
       [ 0,  0,  0],
       [ 0,  1,  0]])

In [223]:
arr1 * arr2

array([[2, 2, 2],
       [4, 1, 1],
       [4, 2, 1]])

In [224]:
arr1

array([[1, 1, 2],
       [2, 1, 1],
       [2, 2, 1]])

In [225]:
arr2

array([[2, 2, 1],
       [2, 1, 1],
       [2, 1, 1]])

matrix multiplication

In [226]:
arr1 @ arr2

array([[ 8,  5,  4],
       [ 8,  6,  4],
       [10,  7,  5]])

In [227]:
arr1

array([[1, 1, 2],
       [2, 1, 1],
       [2, 2, 1]])

In [228]:
arr2

array([[2, 2, 1],
       [2, 1, 1],
       [2, 1, 1]])

index by division

In [229]:
arr1/arr2

array([[0.5, 0.5, 2. ],
       [1. , 1. , 1. ],
       [1. , 2. , 1. ]])

In [230]:
arr1

array([[1, 1, 2],
       [2, 1, 1],
       [2, 2, 1]])

In [231]:
arr1 / 0

<ipython-input-231-f39b50d43667>:1: RuntimeWarning: divide by zero encountered in divide
  arr1 / 0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

**Broad casting**

In [232]:
arr = np.zeros((3, 4))

In [233]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [234]:
arr + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [235]:
arr


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [237]:
a = np.array([1,2,3,4])

In [238]:
a

array([1, 2, 3, 4])

In [239]:
a.shape

(4,)

In [240]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [241]:
arr + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [242]:
a = np.array([1, 2, 3])

In [243]:
a = np.array([[1, 2, 3]])

In [244]:
a.T

array([[1],
       [2],
       [3]])

In [245]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [246]:
a

array([[1, 2, 3]])

In [247]:
arr + a.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [248]:
a = np.array([1, 2, 3])
a.T

array([1, 2, 3])

In [249]:
arr1

array([[1, 1, 2],
       [2, 1, 1],
       [2, 2, 1]])

In [250]:
np.sqrt(arr1)

array([[1.        , 1.        , 1.41421356],
       [1.41421356, 1.        , 1.        ],
       [1.41421356, 1.41421356, 1.        ]])

In [251]:
np.log10(arr1)

array([[0.     , 0.     , 0.30103],
       [0.30103, 0.     , 0.     ],
       [0.30103, 0.30103, 0.     ]])

In [252]:
np.exp(arr1)

array([[2.71828183, 2.71828183, 7.3890561 ],
       [7.3890561 , 2.71828183, 2.71828183],
       [7.3890561 , 7.3890561 , 2.71828183]])

In [253]:
a

array([1, 2, 3])

In [254]:
np.min(a)

1

In [255]:
arr1

array([[1, 1, 2],
       [2, 1, 1],
       [2, 2, 1]])

In [256]:
np.min(arr1)

1

In [257]:
arr1

array([[1, 1, 2],
       [2, 1, 1],
       [2, 2, 1]])

In [258]:
arr1.T

array([[1, 2, 2],
       [1, 1, 2],
       [2, 1, 1]])

reduce higher dimension to the 1 d

In [259]:
arr1.flatten()

array([1, 1, 2, 2, 1, 1, 2, 2, 1])

Expend_dimension
- expends the array by inserting a new axis

In [260]:
arr = np.array([[1, 2, 3], [4, 5, 6], [1, 2, 3]])

In [261]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [262]:
np.sum(arr)

27

In [263]:
np.sum(arr, axis = 0)

array([ 6,  9, 12])

In [264]:
np.sum(arr, axis =1 )

array([ 6, 15,  6])

**expend dimension of array**

In [265]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [266]:
arr.ndim

1

In [268]:
arr1 = np.expand_dims(arr, axis = 0)

In [269]:
arr1

array([[1, 2, 3, 4]])

In [270]:
arr1.ndim

2

In [271]:
arr2 = np.expand_dims(arr1, axis = 0)

In [272]:
arr2

array([[[1, 2, 3, 4]]])

In [273]:
arr2.shape

(1, 1, 4)

In [274]:
arr

array([1, 2, 3, 4])

In [275]:
arr1 = np.expand_dims(arr, axis =1)

In [276]:
arr1

array([[1],
       [2],
       [3],
       [4]])

In [277]:
arr = np.zeros((3, 4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [278]:
arr1 = np.expand_dims(arr, axis = 1)

In [279]:
arr1

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [280]:
arr1 = np.expand_dims(arr, axis = 0)

In [281]:
arr1

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [283]:
import numpy as np

#Examples matrices
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

#using np.dot for matrix multiplecation
matrix_product = np.dot(A, B)
print("Matrix product using np.dot : \n", matrix_product)

#Using @ operator for matrix multiplication
matrix_product = A @ B
print(matrix_product)

Matrix product using np.dot : 
 [[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [289]:
import numpy as np
import time

#  Generate two random NumPy arrays with one million elements each
array1 = np.random.rand(1000000)
array2 = np.random.rand(1000000)

# Measure time for the vectorized version using np.dot
start_time_vectorized = time.time()
result_vectorized = np.dot(array1, array2)
end_time_vectorized = time.time()

print("Time taken for vectorized calculation: " + str(1000 * (end_time_vectorized - start_time_vectorized)) + " milliseconds")

Time taken for vectorized calculation: 1.440286636352539 milliseconds


In [290]:
# Reset result_vectorized to 0
result_vectorized = 0

#Measure time for the version using a loop
start_time_for_loop = time.time()
for index in range(1000000):
  result_vectorized += array1[index] * array2[index]
end_time_for_loop = time.time()

print("Time taken for calculation using a for loop: " + str(1000 * (end_time_for_loop - start_time_for_loop)) + " milliseconds")

Time taken for calculation using a for loop: 950.9930610656738 milliseconds
